---
language: python
env:
# - MATE=1.19 ATRIL=atril-1.19.0
addons:
  apt:
    sources:
    packages:
    - aria2
    - bsdtar
    - empty-expect
    - qemu

install:
- pip install pexpect
- qemu-system-i386 --version
- qemu-system-i386 -machine help
- qemu-system-x86_64 --version
- qemu-system-x86_64 -machine help
- qemu-system-arm -machine help
- aria2c https://archive.openwrt.org/snapshots/trunk/realview/generic/openwrt-realview-vmlinux-initramfs.elf
# - empty -L log -f qemu-system-arm -M realview-eb-mpcore -kernel openwrt-realview-vmlinux-initramfs.elf -nographic
#^ Strange: -L log seems to need to be there.
# - empty -v -w "Please press Enter to activate this console." "\n"
# - empty -w "root@(none):/#" "uname -a"
# - empty -w "root@(none):/#" "halt" # poweroff
- python openwrt.py
- aria2c --seed-time=0 --bt-enable-lpd=true https://www.finnix.org/releases/111/finnix-111.iso.torrent
- aria2c --seed-ratio=0.0 --bt-enable-lpd=true finnix-111.iso.torrent &
- ls -l
- du -sch *
- install --directory finnix
- bsdtar -C finnix -xf finnix-111.iso
- ls finnix/boot/x86
- ls finnix/finnix/arch/x86/root.img
- python finnix.py
- ls -l finnix/finnix/arch/x86/root.img
- chmod u+w finnix/finnix/arch/x86/root.img
- ls -l finnix/finnix/arch/x86/root.img

script:
# - qemu-system-x86_64 -kernel finnix/boot/x86/linux64 -append 'initrd=boot/x86/initrd.xz console=ttyS0' -hda finnix/finnix/arch/x86/root.img -cdrom finnix-111.iso -nographic
- qemu-system-x86_64 -kernel finnix/boot/x86/linux64 -append 'initrd=boot/x86/initrd.xz console=ttyS0 root=finnix/arch/x86/root.img ro' -cdrom finnix-111.iso -nographic
# findiso=
