---
language: python
env:
# - MATE=1.19 ATRIL=atril-1.19.0
addons:
  apt:
    sources:
    packages:
    - aria2
    - empty-expect
    - qemu

install:
- pip install pexpect
- qemu-system-i386 --version
- aria2c https://archive.openwrt.org/snapshots/trunk/realview/generic/openwrt-realview-vmlinux-initramfs.elf
# - empty -L log -f qemu-system-arm -M realview-eb-mpcore -kernel openwrt-realview-vmlinux-initramfs.elf -nographic
#^ Strange: -L log seems to need to be there.
# - empty -v -w "Please press Enter to activate this console." "\n"
# - empty -w "root@(none):/#" "uname -a"
# - empty -w "root@(none):/#" "halt" # poweroff
- python openwrt.py
- aria2c --seed-time=0 --bt-enable-lpd=true https://www.finnix.org/releases/111/finnix-111.iso.torrent
- aria2c --seed-ratio=0.0 --bt-enable-lpd=true finnix-111.iso.torrent &
- ls -l
- du -sch *
- python finnix.py

script:
- qemu-system-i386 --version
- qemu-system-x86_64 -cdrom finnix-111.iso -nographic
