---
# language: 
env:
# - MATE=1.19 ATRIL=atril-1.19.0
addons:
  apt:
    sources:
    packages:
    - aria2
    # - empty-expect
    - qemu

install:
- qemu-system-i386 --version
- aria2c https://archive.openwrt.org/snapshots/trunk/realview/generic/openwrt-realview-vmlinux-initramfs.elf
- qemu-system-arm -M realview-eb-mpcore -kernel openwrt-realview-vmlinux-initramfs.elf -nographic

script:
- qemu-system-i386 --version
