---
# language: 
env:
# - MATE=1.19 ATRIL=atril-1.19.0
addons:
  apt:
    sources:
    packages:
    - aria2
    - empty-expect
    - qemu

install:
- qemu-system-i386 --version
- aria2c https://archive.openwrt.org/snapshots/trunk/realview/generic/openwrt-realview-vmlinux-initramfs.elf
- echo '\n'
- echo "\n"
- empty -f qemu-system-arm -M realview-eb-mpcore -kernel openwrt-realview-vmlinux-initramfs.elf -nographic
- empty -l
- cat /tmp/empty.*.out
- empty -w 'Please press Enter to activate this console.' '\n'
- empty -l
- empty -w "root@(none):/#" "uname -a"
- empty -w "root@(none):/#" "halt" # poweroff
- empty -l

script:
- qemu-system-i386 --version
